apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
  name: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.pushover: uwjm3jdi3fs5dqdzwzidysjsrmzkpb
    notifications.argoproj.io/subscribe.on-sync-succeeded.pushover: uwjm3jdi3fs5dqdzwzidysjsrmzkpb
spec:
  project: argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  source:
    repoURL: https://github.com/DeNic0la/argocd-infra.git
    targetRevision: main
    path: '.'
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    retry:
      refresh: true
      backoff:
        duration: 3m
        factor: 3
        maxDuration: 5m
    automated:
      selfHeal: false
      allowEmpty: false
      prune: false
      enabled: true



  