apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
spec:
  project: n8n
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: n8n
  source:
    repoURL: https://github.com/DeNic0la/n8n-infra.git
    targetRevision: main
    path: '.'


