apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: konfi
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - namespace: konfi-dev
            revision: dev
            path: stages/dev
          - namespace: konfi
            revision: main
            path: stages/prod
  template:
    metadata:
      name: '{{.namespace}}'
      annotations:
        pref.argocd.argoproj.io/default-view: pods
        pref.argocd.argoproj.io/default-pod-sort: topLevelResource
    spec:
      project: konfi
      source:
        repoURL: https://github.com/DeNic0la/konfi-infra.git
        targetRevision: '{{.revision}}'
        path: '{{.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.namespace}}'
      syncPolicy:
        syncOptions:
          - RespectIgnoreDifferences=true
        automated:
          enabled: true
          allowEmpty: false
          selfHeal: false
          prune: true

